# Telescope DNS Configure File
# https://github.com/wolf-joe/ts-dns

listen = ":53"

[hosts]
"google.com" = "1.1.1.1"

[groups]
  [groups.clean]
  dns = ["223.5.5.5", "114.114.114.114"]
  concurrent = true

  [groups.dirty]
  dns = ["208.67.222.222:5353", "176.103.130.130:5353"]
  gfwlist_file = "gfwlist.txt"
